version: "3.9"

services: 
    kdan:
        container_name: api
        build:
          context: ./
          dockerfile: ./Dockerfile
        ports:
          - "5000:5000"
          - "5001:5001"
          - "5002:5002"
          - "7071:7071"
        depends_on:
          - postgesql
        restart: always
        volumes:
          - ./:/app
        networks:
          - kdan_web
    postgesql:
        image: postgres:15-alpine
        container_name: postgesql
        ports:
        - "5432:5432"
        restart: always
        environment:
          - POSTGRES_USER=kdan
          - POSTGRES_PASSWORD=kdan
          - POSTGRES_DB=kdan
        volumes:
          - ./pgdata:/var/lib/postgresql/data
        networks:
          - kdan_web
    swagger-ui:
        image: swaggerapi/swagger-ui
        container_name: swagger_ui
        ports:
        - "1001:8080"
        volumes:
          - ./doc:/usr/share/nginx/html/doc
        environment:
          API_URL: doc/kdan/kdan.swagger.json

networks:
    kdan_web:
        driver: bridge