// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package data

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Mask struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type MaskPrice struct {
	MaskID     int32   `json:"mask_id"`
	PharmacyID int32   `json:"pharmacy_id"`
	Price      float64 `json:"price"`
}

type Pharmacy struct {
	ID                      int32                                        `json:"id"`
	Name                    string                                       `json:"name"`
	OpeningHours            pgtype.Multirange[pgtype.Range[pgtype.Int4]] `json:"opening_hours"`
	OpeningHoursDescription string                                       `json:"opening_hours_description"`
	CashBalance             *float64                                     `json:"cash_balance"`
}

type PurchaseHistory struct {
	ID                int32     `json:"id"`
	UserID            int32     `json:"user_id"`
	PharmacyID        int32     `json:"pharmacy_id"`
	MaskID            int32     `json:"mask_id"`
	TransactionAmount float64   `json:"transaction_amount"`
	TransactionDate   time.Time `json:"transaction_date"`
}

type User struct {
	ID          int32    `json:"id"`
	Name        string   `json:"name"`
	CashBalance *float64 `json:"cash_balance"`
}
