// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.2

package data

import (
	"context"
)

type Querier interface {
	CreateMask(ctx context.Context, name string) (Mask, error)
	CreateMaskPrice(ctx context.Context, arg CreateMaskPriceParams) error
	CreatePharmacy(ctx context.Context, arg CreatePharmacyParams) (Pharmacy, error)
	CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (PurchaseHistory, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetAggTransactionsByDateRange(ctx context.Context, arg GetAggTransactionsByDateRangeParams) ([]GetAggTransactionsByDateRangeRow, error)
	GetMaskPriceById(ctx context.Context, arg GetMaskPriceByIdParams) (float64, error)
	GetMasksByNameRelevancy(ctx context.Context, name string) ([]Mask, error)
	GetPharmaciesByNameRelevancy(ctx context.Context, name string) ([]Pharmacy, error)
	GetPharmaciesByTime(ctx context.Context, time int32) ([]Pharmacy, error)
	GetPharmaciesMaskCountsByMaskPriceRange(ctx context.Context, arg GetPharmaciesMaskCountsByMaskPriceRangeParams) ([]GetPharmaciesMaskCountsByMaskPriceRangeRow, error)
	GetSoldMasksByPharmacy(ctx context.Context, arg GetSoldMasksByPharmacyParams) ([]GetSoldMasksByPharmacyRow, error)
	GetTopXUsersTransactionByDateRange(ctx context.Context, arg GetTopXUsersTransactionByDateRangeParams) ([]GetTopXUsersTransactionByDateRangeRow, error)
	PurchaseMaskFromPharmacy(ctx context.Context, arg PurchaseMaskFromPharmacyParams) (PurchaseHistory, error)
	UpdatePharmacyCashBalance(ctx context.Context, arg UpdatePharmacyCashBalanceParams) error
	UpdateUserCashBalance(ctx context.Context, arg UpdateUserCashBalanceParams) error
}

var _ Querier = (*Queries)(nil)
