server:
  Name: Kdan
  Description: phantom mask
  Port: :5000
  HttpPort: :5001
  PprofPort: :5002
  Mode: Development
  ReadTimeout: 5
  WriteTimeout: 5
  CtxDefaultTimeout: 12
  Debug: true

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: console
  Level: info
  Mode: Development

postgres:
  PostgresqlHost: localhost
  PostgresqlPort: 5432
  PostgresqlUser: kdan
  PostgresqlPassword: kdan
  PostgresqlDbname: kdan
  PostgresqlSslmode: false
  PgDriver: pgx

healthCheck:
  Url: 0.0.0.0:7071
  ServiceName: Kdan
  Path: /health