// @proto/ type following command to build pb.go
// protoc --proto_path=./ --go_out=./ --go-grpc_out=./ --grpc-gateway_out ./ --go_opt=paths=source_relative --go-grpc_opt=paths=source_relative --grpc-gateway_opt logtostderr=true --grpc-gateway_opt=paths=source_relative pharmacy/pharmacy.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.18.0--rc2
// source: pharmacy/pharmacy.proto

package pharmacyProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pharmacy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int32   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	OpeningHours string  `protobuf:"bytes,3,opt,name=opening_hours,json=openingHours,proto3" json:"opening_hours,omitempty"`
	CashBalance  float32 `protobuf:"fixed32,4,opt,name=cash_balance,json=cashBalance,proto3" json:"cash_balance,omitempty"`
}

func (x *Pharmacy) Reset() {
	*x = Pharmacy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pharmacy_pharmacy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pharmacy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pharmacy) ProtoMessage() {}

func (x *Pharmacy) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pharmacy.ProtoReflect.Descriptor instead.
func (*Pharmacy) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{0}
}

func (x *Pharmacy) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pharmacy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pharmacy) GetOpeningHours() string {
	if x != nil {
		return x.OpeningHours
	}
	return ""
}

func (x *Pharmacy) GetCashBalance() float32 {
	if x != nil {
		return x.CashBalance
	}
	return 0
}

type Mask struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Mask) Reset() {
	*x = Mask{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pharmacy_pharmacy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Mask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mask) ProtoMessage() {}

func (x *Mask) ProtoReflect() protoreflect.Message {
	mi := &file_pharmacy_pharmacy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Mask.ProtoReflect.Descriptor instead.
func (*Mask) Descriptor() ([]byte, []int) {
	return file_pharmacy_pharmacy_proto_rawDescGZIP(), []int{1}
}

func (x *Mask) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Mask) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_pharmacy_pharmacy_proto protoreflect.FileDescriptor

var file_pharmacy_pharmacy_proto_rawDesc = []byte{
	0x0a, 0x17, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x79, 0x2f, 0x70, 0x68, 0x61, 0x72, 0x6d,
	0x61, 0x63, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x70, 0x68, 0x61, 0x72, 0x6d,
	0x61, 0x63, 0x79, 0x22, 0x76, 0x0a, 0x08, 0x50, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x79, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x12, 0x23, 0x0a, 0x0d, 0x6f, 0x70, 0x65, 0x6e, 0x69, 0x6e, 0x67, 0x5f, 0x68,
	0x6f, 0x75, 0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x6f, 0x70, 0x65, 0x6e,
	0x69, 0x6e, 0x67, 0x48, 0x6f, 0x75, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x61, 0x73, 0x68,
	0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x0b,
	0x63, 0x61, 0x73, 0x68, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x22, 0x2a, 0x0a, 0x04, 0x4d,
	0x61, 0x73, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4a, 0x61, 0x6d, 0x65, 0x73, 0x48, 0x73, 0x75, 0x33, 0x33,
	0x33, 0x2f, 0x6b, 0x64, 0x61, 0x6e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x68, 0x61,
	0x72, 0x6d, 0x61, 0x63, 0x79, 0x3b, 0x70, 0x68, 0x61, 0x72, 0x6d, 0x61, 0x63, 0x79, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pharmacy_pharmacy_proto_rawDescOnce sync.Once
	file_pharmacy_pharmacy_proto_rawDescData = file_pharmacy_pharmacy_proto_rawDesc
)

func file_pharmacy_pharmacy_proto_rawDescGZIP() []byte {
	file_pharmacy_pharmacy_proto_rawDescOnce.Do(func() {
		file_pharmacy_pharmacy_proto_rawDescData = protoimpl.X.CompressGZIP(file_pharmacy_pharmacy_proto_rawDescData)
	})
	return file_pharmacy_pharmacy_proto_rawDescData
}

var file_pharmacy_pharmacy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pharmacy_pharmacy_proto_goTypes = []interface{}{
	(*Pharmacy)(nil), // 0: pharmacy.Pharmacy
	(*Mask)(nil),     // 1: pharmacy.Mask
}
var file_pharmacy_pharmacy_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pharmacy_pharmacy_proto_init() }
func file_pharmacy_pharmacy_proto_init() {
	if File_pharmacy_pharmacy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pharmacy_pharmacy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pharmacy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pharmacy_pharmacy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Mask); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pharmacy_pharmacy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pharmacy_pharmacy_proto_goTypes,
		DependencyIndexes: file_pharmacy_pharmacy_proto_depIdxs,
		MessageInfos:      file_pharmacy_pharmacy_proto_msgTypes,
	}.Build()
	File_pharmacy_pharmacy_proto = out.File
	file_pharmacy_pharmacy_proto_rawDesc = nil
	file_pharmacy_pharmacy_proto_goTypes = nil
	file_pharmacy_pharmacy_proto_depIdxs = nil
}
